blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/articles", to:"articles#index"
  get "/articles", to:"articles#create"
  get "/articles/new", to:"articles#new"
  #get "/articles/change", to:"articles#change"
  get "/articles/:id", to:"articles#show", as: :article
  root "articles#index"
  #root "posts#index"

  #resources :articles
  # Defines the root path route ("/")
  # root "articles#index"
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

blog/app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :content ,presence: true, length: {minimum: 10}
end

blog/app/models/post.rb
class Post < ApplicationRecord
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles= Article.all
    end
    
    def show
        @article= Article.find(params[:id])
    end

    def new
        @article= Article.new
    end

    def create
        @article= Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render :new, status: :unprocessable_entity
        end
    end

    private
      def article_params
        params.require(:article).permit(:title, :content)
      end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :email)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/articles/index.html.erb
<h1>This is the program</h1>
<ul>
  <% @articles.each do |article|%>
    <li>
      <!--<a href="/articles/<%= article.id%>">-->
      <strong><%= article.title%></strong></a>
    </li>
<p><%= article.content %></p>
<%= link_to article.title, article%>
<%= link_to "New",articles_new_path %>-->
<% end %>
</ul>

blog/app/views/articles/new.html.erb
<h1>New article</h1>
<% form_with model: @article do |form| %>
<%= form.label :title %>
<%= form.text_field :title %>
  <% @article.errors.full_messages_for(:title).each do |message| %>
    <div><%= message%></div>
  <% end %>
</div>

<div>
  <%= form.label :content %>
  <% form.text_area :content %>
  <% @article.errors.full_messages_for(:content).each do |message| %>
    <div><%= message%></div>
  <% end %>
</div>

<div>
  <%= form.submit %>
</div>

<% end %>

blog/app/views/articles/show.html.erb
  <%= @article.title %>
  <p><%= @article.content %></p>
  <%= link_to "HomePage", root_path%>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Name:</strong>
    <%= post.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= post.email %>
  </p>

</div>

blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

blog/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

blog/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>